// Compile official HeroUI components locally; no CDN or UI runtime framework.
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const {execFileSync} = require('node:child_process');
const root = path.resolve(__dirname, '..');
const pkg = path.join(root, 'node_modules/@heroui/styles');
const {version} = JSON.parse(fs.readFileSync(path.join(pkg, 'package.json'), 'utf8'));
const license = fs.readFileSync(path.join(pkg, 'LICENSE'), 'utf8');
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'l5pha-ui-'));
try {
  const compiled = path.join(temp, 'heroui.css');
  execFileSync(process.execPath, [path.join(root, 'node_modules/@tailwindcss/cli/dist/index.mjs'),
    '-i', 'ui/heroui.css', '-o', compiled, '--minify'], {cwd:root, stdio:'pipe'});
  const upstream = fs.readFileSync(compiled, 'utf8');
  const theme = fs.readFileSync(path.join(root, 'ui/l5pha.css'), 'utf8');
  const result = `/* Generated by npm run build:ui. Edit ui/l5pha.css.\n * HeroUI @heroui/styles ${version}\n${license}\n*/\n${upstream}\n${theme}`;
  fs.writeFileSync(path.join(root, 'src/veyquant/web/app.css'), result);
  console.log(`L5PHA UI · HeroUI ${version} · ${Buffer.byteLength(result)} bytes`);
} finally { fs.rmSync(temp, {recursive:true, force:true}); }
