"""Bundle reviewed Lambda modules into a reproducible CloudFormation template."""

import base64
import hashlib
import json
import zlib
from pathlib import Path
from textwrap import indent


def main():
    root = Path(__file__).resolve().parents[1]
    base = (root / "infra/analysis.base.yaml").read_text()
    files = {
        name: (root / "src/veyquant" / name).read_text()
        for name in (
            "__init__.py",
            "shadow_inference.py",
            "research_sources.py",
            "native_search.py",
            "input_budget.py",
            "model_prompts.py",
        )
    }
    bundle = json.dumps(files, sort_keys=True).encode()
    prefix, tail = base.split("        ZipFile: |\n", 1)
    _, suffix = tail.split("  AnalysisVersion:\n", 1)
    digest = hashlib.sha256(bundle).hexdigest()
    payload = base64.b64encode(zlib.compress(bundle, 9)).decode()
    # This is packaging of reviewed repository sources, not downloaded executable code.
    encoded_source = (
        "import base64, hashlib, json, sys, zlib\nfrom pathlib import Path\n"
        f"BUNDLE = {payload!r}\n"
        f"DIGEST = {digest!r}\n"
        "raw = zlib.decompress(base64.b64decode(BUNDLE))\n"
        "assert hashlib.sha256(raw).hexdigest() == DIGEST\n"
        "root = Path('/tmp') / ('veyquant-' + DIGEST)\n"
        "package = root / 'veyquant'\npackage.mkdir(parents=True, exist_ok=True)\n"
        "for name, source in json.loads(raw).items():\n"
        "    assert name in {'__init__.py', 'shadow_inference.py', "
        "'research_sources.py', 'native_search.py', 'input_budget.py', 'model_prompts.py'}\n"
        "    (package / name).write_text(source)\n"
        "sys.path.insert(0, str(root))\n"
        "from veyquant.shadow_inference import handler\n"
    )
    content = (
        prefix
        + "        ZipFile: |\n"
        + indent(encoded_source, "          ")
        + "  AnalysisVersion:\n"
        + suffix
    )
    content = content.replace("AnalysisVersion", "AnalysisVersion" + digest[:12])
    content = (
        "# Generated by scripts/render_analysis_template.py; source SHA256: "
        + digest
        + "\n"
        + content
    )
    if len(content.encode()) > 51200:
        raise SystemExit("template_too_large")
    (root / "infra/analysis.yaml").write_text(content)
    print("Rendered analysis.yaml with immutable code version")


if __name__ == "__main__":
    main()
